psql -U postgres -d postgres -f C:\Users\ashley.soto\Documents\Proyectos\Control_gastos\database\schema.sql
psql -U postgres -d postgres -f C:\Users\ashley.soto\Documents\Proyectos\Control_gastos\database\migrations\001_add_pagos_tarjetas.sql
psql -U postgres -d postgres -f C:\Users\ashley.soto\Documents\Proyectos\Control_gastos\database\migrations\002_add_cuotas_msi_view.sql
psql -U postgres -d postgres -f C:\Users\ashley.soto\Documents\Proyectos\Control_gastos\database\migrations\003_add_pago_mensual_view.sql
psql -U postgres -d postgres -f C:\Users\ashley.soto\Documents\Proyectos\Control_gastos\database\migrations\004_update_pago_periodo_view.sql
psql -U postgres -d postgres -f C:\Users\ashley.soto\Documents\Proyectos\Control_gastos\database\migrations\001_add_celular_to_usuarios.sql
psql -U postgres -d postgres -f C:\Users\ashley.soto\Documents\Proyectos\Control_gastos\database\migrations\002_fix_saldo_tarjeta_msi.sql
psql -U postgres -d postgres -f C:\Users\ashley.soto\Documents\Proyectos\Control_gastos\database\migrations\003_add_sessions_and_logs.sql
psql -U postgres -d postgres -f C:\Users\ashley.soto\Documents\Proyectos\Control_gastos\database\migrations\004_add_es_admin_to_usuarios.sql
psql -U postgres -d postgres -f C:\Users\ashley.soto\Documents\Proyectos\Control_gastos\database\migrations\004_update_pago_periodo_view.sql
psql -U postgres -d postgres -f C:\Users\ashley.soto\Documents\Proyectos\Control_gastos\database\migrations\005_add_tipo_tarjeta.sql
psql -U postgres -d postgres -f C:\Users\ashley.soto\Documents\Proyectos\Control_gastos\database\migration_add_terminos_privacidad.sql
psql -U postgres -d postgres -f C:\Users\ashley.soto\Documents\Proyectos\Control_gastos\database\migrations\007_add_prestamos_table.sql
psql -U postgres -d postgres -f C:\Users\ashley.soto\Documents\Proyectos\Control_gastos\database\migrations\006_add_pagos_to_periodo_view.sql
psql -U postgres -d postgres -f C:\Users\ashley.soto\Documents\Proyectos\Control_gastos\database\migrations\005_migrate_pagos_tarjetas_to_egresos.sql